### ISSUE TITLE
[feature suggestion] sync settings across multiple FF instances by utilizing FF sync

### ISSUE THREAD

**Issue by ghost** [maxnikulin/alt-tong#1]
It would be helpful to sync the settings across various Firefox instance. Perhaps it could be achieved through FF sync, like this [extention implemented it](https://github.com/snyderp/web-api-manager/commit/2fab1056204348dce6864ff6a8133da3c8fd977e)

**Comment by maxnikulin** [comment]
I do not promise that I will implement sync soon.

I have an idea that might make the extension auto configuring for significant part of users (if it would be more than a handful of them). Two top languages may be swapped to obtain alternative Accept-Language  header. English may be a fallback if the primary language is not en and there are no better guess. I hope that the extension can just work immediately after install.

Another point is that I have not try to write automatic tests for extension yet. That is why I can be resistant to touch the code that perfectly cover my requirements. Actually the purpose was to get some impression of WebExtensions API.

By the way, could you, please, briefly describe a scenario when it becomes worth to sync such settings? The extension is relying on UI that is unsupported on Android. Are you using "public" computers e.g. in campus that do not share user's profile?

**Comment by ghost** [comment]
One user may utilize the FF browser in different environments, e.g. virtual/cloud/private/corporate/public (FF portable) machines with different OS (Win, Linux, Mac) but with the same profile (synchronising the profile through FF sync.

Never mind though and and perfectly understanding your plausible reasoning I am closing this
